pull_request_rules:
  - name: Add bazel label if a Bazel file is modified
    conditions:
      - files~=\.(bazel|bzl)$
    actions:
      label:
        add:
          - bazel
  - name: Add make label if a Make file is modified
    conditions:
      - files~=(Makefile|\.mk)$
    actions:
      label:
        add:
          - make
  - name: Add comment if only bazel is touched
    conditions:
      - and:
        - files~=\.(bazel|bzl)$
        - -files~=(Makefile|\.mk)$
        - head!=bump-rules_erlang
        - -head~=bump-rbe-
        - -head~=mergify/bp/
    actions:
      comment:
        message: This pull request modifies the bazel build only. If it is a deps update or app_env change, remember to sync any changes to the makefiles.
  - name: Add comment if only make is touched
    conditions:
      - and:
        - files~=(Makefile|\.mk)$
        - -files~=\.(bazel|bzl)$
        - -head~=mergify/bp/
    actions:
      comment:
        message: This pull request modifies the erlang.mk build only. If it is a deps update or PROJECT_ENV change, remember to sync any changes to the bazel files.
  - name: Automatically backport to v3.11.x based on label
    conditions:
      - base=master
      - label=backport-v3.11.x
      - label!=backport-v3.10.x
      - label!=backport-v3.9.x
      - label!=backport-v3.8.x
    actions:
      backport:
        branches:
          - v3.11.x
        assignees:
          - "{{ author }}"
  - name: Automatically backport to v3.11.x & v3.10.x based on label
    conditions:
      - base=master
      - label=backport-v3.11.x
      - label=backport-v3.10.x
      - label!=backport-v3.9.x
      - label!=backport-v3.8.x
    actions:
      backport:
        branches:
          - v3.11.x
        labels:
          - backport-v3.10.x
        assignees:
          - "{{ author }}"
  - name: Automatically backport to v3.11.x, v3.10.x & v3.9.x based on labels
    conditions:
      - base=master
      - label=backport-v3.11.x
      - label=backport-v3.10.x
      - label=backport-v3.9.x
      - label!=backport-v3.8.x
    actions:
      backport:
        branches:
          - v3.11.x
        labels:
          - backport-v3.10.x
          - backport-v3.9.x
        assignees:
          - "{{ author }}"
  - name: Automatically backport to v3.11.x, v3.10.x, v3.9.x & v3.8.x based on labels
    conditions:
      - base=master
      - label=backport-v3.11.x
      - label=backport-v3.10.x
      - label=backport-v3.9.x
      - label=backport-v3.8.x
    actions:
      backport:
        branches:
          - v3.11.x
        labels:
          - backport-v3.10.x
          - backport-v3.9.x
          - backport-v3.8.x
        assignees:
          - "{{ author }}"
  - name: Automatically backport to v3.10.x based on label
    conditions:
      - base=v3.11.x
      - label=backport-v3.10.x
      - label!=backport-v3.9.x
      - label!=backport-v3.8.x
    actions:
      backport:
        branches:
          - v3.10.x
        assignees:
          - "{{ author }}"
  - name: Automatically backport to v3.10.x & v3.9.x based on labels
    conditions:
      - base=v3.11.x
      - label=backport-v3.10.x
      - label=backport-v3.9.x
      - label!=backport-v3.8.x
    actions:
      backport:
        branches:
          - v3.10.x
        labels:
          - backport-v3.9.x
        assignees:
          - "{{ author }}"
  - name: Automatically backport to v3.10.x, v3.9.x & v3.8.x based on labels
    conditions:
      - base=v3.11.x
      - label=backport-v3.10.x
      - label=backport-v3.9.x
      - label=backport-v3.8.x
    actions:
      backport:
        branches:
          - v3.10.x
        labels:
          - backport-v3.9.x
          - backport-v3.8.x
        assignees:
          - "{{ author }}"
  - name: Automatically backport to v3.9.x based on label
    conditions:
      - base=v3.10.x
      - label=backport-v3.9.x
      - label!=backport-v3.8.x
    actions:
      backport:
        branches:
          - v3.9.x
        assignees:
          - "{{ author }}"
  - name: Automatically backport to v3.9.x & v3.8.x based on labels
    conditions:
      - base=v3.10.x
      - label=backport-v3.9.x
      - label=backport-v3.8.x
    actions:
      backport:
        branches:
          - v3.9.x
        labels:
          - backport-v3.8.x
        assignees:
          - "{{ author }}"
  - name: Automatically backport to v3.8.x based on label
    conditions:
      - base=v3.9.x
      - label=backport-v3.8.x
    actions:
      backport:
        branches:
          - v3.8.x
        assignees:
          - "{{ author }}"
