name: GNU Make Smoke Test
on:
  workflow_dispatch:
  push:
    branches:
    - rin/makefile-updates
jobs:
  test:
    name: GNU Make Smoke Test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
        - erlang_version: "25.1"
          elixir_version: 1.14.0
    timeout-minutes: 240
    steps:
    - name: CHECKOUT REPOSITORY
      uses: actions/checkout@v3
    - name: CONFIGURE ERLANG
      uses: erlef/setup-beam@v1.15
      with:
        otp-version: ${{ matrix.erlang_version }}
        elixir-version: ${{ matrix.elixir_version }}
    - name: BUILD
      run: |
        make
    - name: CHECK rabbit_common
      run: |
        make -C deps/rabbit_common check
    - name: TEST rabbitmq_cli
      run: |
        make start-background-broker \
          RABBITMQ_VERSION=3.12.0 \
          PLUGINS="rabbitmq_stomp rabbitmq_federation rabbitmq_stream_management"

        make -C deps/rabbitmq_cli tests

        make stop-node
    - name: CT-FAST rabbit
      run: |
        make -C deps/rabbit ct-fast
    - name: UPLOAD TEST ARTIFACTS
      if: always()
      uses: actions/upload-artifact@v3.1.1
      with:
        name: deps-rabbit-logs-${{ matrix.erlang_version }}-${{ matrix.elixir_version }}
        path: |
          deps/rabbit/logs
