name: Test rabbit_common
on:
  workflow_call:
    inputs:
      trc:
        required: true
        type: string
      hash:
        required: true
        type: string
      ignore-dialyze-errors:
        type: boolean
jobs:
  test:
    name: Test rabbit_common
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        otp_version:
        - 26.2
        metadata_store:
        - mnesia
        - khepri
    timeout-minutes: 180
    env:
      SUCCESS_PATH: ${{ inputs.trc }}/${{ inputs.hash }}/rabbit_common/${{ matrix.metadata_store }}/${{ matrix.otp_version }}
    steps:
    - name: FETCH TEST RESULT CACHE
      uses: actions/download-artifact@v4
      with:
        name: test-result-cache-subdir
        path: ${{ inputs.trc }}
    - name: CHECKOUT REPOSITORY
      uses: actions/checkout@v4
    - name: SETUP ERLANG/ELIXIR
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        elixir-version: 1.15
    - name: BUILD
      run: |
        make \
          RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
        mkdir -p ${{ env.SUCCESS_PATH }}
    - name: XREF
      run: |
        if [[ -f ${{ env.SUCCESS_PATH }}/xref ]]; then
          echo "xref already passed for this key ${{ inputs.hash }}"
        else
          make -C deps/rabbit_common \
              xref \
              RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
          touch ${{ env.SUCCESS_PATH }}/xref
        fi
    - name: DIALYZE
      run: |
        if [[ -f ${{ env.SUCCESS_PATH }}/dialyze ]]; then
          echo "dialyze already passed for this key ${{ inputs.hash }}"
        else
          make -C deps/rabbit_common \
              dialyze \
              RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
          touch ${{ env.SUCCESS_PATH }}/dialyze
        fi
      continue-on-error: ${{ inputs.ignore-dialyze-errors }}
    - name: EUNIT
      run: |
        if [[ -f ${{ env.SUCCESS_PATH }}/eunit ]]; then
          echo "eunit already passed for this key ${{ inputs.hash }}"
        else
          make -C deps/rabbit_common \
              eunit \
              RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
          touch ${{ env.SUCCESS_PATH }}/eunit
        fi
    - name: CT rabbit_env
      run: |
        if [[ -f ${{ env.SUCCESS_PATH }}/ct-rabbit_env ]]; then
          echo "ct-rabbit_env already passed for this key ${{ inputs.hash }}"
        else
          make -C deps/rabbit_common \
              ct-rabbit_env \
              RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
          touch ${{ env.SUCCESS_PATH }}/ct-rabbit_env
        fi
    - name: CT supervisor2
      run: |
        if [[ -f ${{ env.SUCCESS_PATH }}/ct-supervisor2 ]]; then
          echo "ct-supervisor2 already passed for this key ${{ inputs.hash }}"
        else
          make -C deps/rabbit_common \
              ct-supervisor2 \
              RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
          touch ${{ env.SUCCESS_PATH }}/ct-supervisor2
        fi
    - name: CT unit
      run: |
        if [[ -f ${{ env.SUCCESS_PATH }}/ct-unit ]]; then
          echo "ct-unit already passed for this key ${{ inputs.hash }}"
        else
          make -C deps/rabbit_common \
              ct-unit \
              RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
          touch ${{ env.SUCCESS_PATH }}/ct-unit
        fi
    - name: CT unit_password_hashing
      run: |
        if [[ -f ${{ env.SUCCESS_PATH }}/ct-unit_password_hashing ]]; then
          echo "ct-unit_password_hashing already passed for this key ${{ inputs.hash }}"
        else
          make -C deps/rabbit_common \
              ct-unit_password_hashing \
              RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
          touch ${{ env.SUCCESS_PATH }}/ct-unit_password_hashing
        fi
    - name: CT unit_priority_queue
      run: |
        if [[ -f ${{ env.SUCCESS_PATH }}/ct-unit_priority_queue ]]; then
          echo "ct-unit_priority_queue already passed for this key ${{ inputs.hash }}"
        else
          make -C deps/rabbit_common \
              ct-unit_priority_queue \
              RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
          touch ${{ env.SUCCESS_PATH }}/ct-unit_priority_queue
        fi
    - name: CT worker_pool
      run: |
        if [[ -f ${{ env.SUCCESS_PATH }}/ct-worker_pool ]]; then
          echo "ct-worker_pool already passed for this key ${{ inputs.hash }}"
        else
          make -C deps/rabbit_common \
              ct-worker_pool \
              RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
          touch ${{ env.SUCCESS_PATH }}/ct-worker_pool
        fi
    - name: SAVE CACHE COPY
      uses: actions/upload-artifact@v4.3.1
      with:
        name: trc-rabbit_common-${{ matrix.metadata_store }}-${{ matrix.otp_version }}
        path: |
          ${{ inputs.trc }}
    - name: UPLOAD TEST ARTIFACTS
      if: always()
      uses: actions/upload-artifact@v4.3.1
      with:
        name: testlogs-rabbit_common-${{ matrix.metadata_store }}-${{ matrix.otp_version }}
        path: deps/rabbit_common/logs/*
