name: Test amqp10_client
on:
  workflow_call:
    inputs:
      trc:
        required: true
        type: string
      hash:
        required: true
        type: string
      ignore-dialyze-errors:
        type: boolean
jobs:
  test:
    name: Test amqp10_client
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        otp_version:
        - 26.2
        metadata_store:
        - mnesia
        - khepri
    timeout-minutes: 180
    env:
      SUCCESS_PATH: ${{ inputs.trc }}/${{ inputs.hash }}/amqp10_client/${{ matrix.metadata_store }}/${{ matrix.otp_version }}
    steps:
    - name: FETCH TEST RESULT CACHE
      uses: actions/download-artifact@v4
      with:
        name: test-result-cache-subdir
        path: ${{ inputs.trc }}
    - name: CHECKOUT REPOSITORY
      uses: actions/checkout@v4
    - name: SETUP ERLANG/ELIXIR
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        elixir-version: 1.15
    - name: BUILD
      run: |
        make \
          RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
        mkdir -p ${{ env.SUCCESS_PATH }}
    - name: XREF
      run: |
        if [[ -f ${{ env.SUCCESS_PATH }}/xref ]]; then
          echo "xref already passed for this key ${{ inputs.hash }}"
        else
          make -C deps/amqp10_client \
              xref \
              RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
          touch ${{ env.SUCCESS_PATH }}/xref
        fi
    - name: DIALYZE
      run: |
        if [[ -f ${{ env.SUCCESS_PATH }}/dialyze ]]; then
          echo "dialyze already passed for this key ${{ inputs.hash }}"
        else
          make -C deps/amqp10_client \
              dialyze \
              RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
          touch ${{ env.SUCCESS_PATH }}/dialyze
        fi
      continue-on-error: ${{ inputs.ignore-dialyze-errors }}
    - name: EUNIT
      run: |
        if [[ -f ${{ env.SUCCESS_PATH }}/eunit ]]; then
          echo "eunit already passed for this key ${{ inputs.hash }}"
        else
          make -C deps/amqp10_client \
              eunit \
              RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
          touch ${{ env.SUCCESS_PATH }}/eunit
        fi
    - name: CT msg
      run: |
        if [[ -f ${{ env.SUCCESS_PATH }}/ct-msg ]]; then
          echo "ct-msg already passed for this key ${{ inputs.hash }}"
        else
          make -C deps/amqp10_client \
              ct-msg \
              RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
          touch ${{ env.SUCCESS_PATH }}/ct-msg
        fi
    - name: CT system
      run: |
        if [[ -f ${{ env.SUCCESS_PATH }}/ct-system ]]; then
          echo "ct-system already passed for this key ${{ inputs.hash }}"
        else
          make -C deps/amqp10_client \
              ct-system \
              RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
          touch ${{ env.SUCCESS_PATH }}/ct-system
        fi
    - name: SAVE CACHE COPY
      uses: actions/upload-artifact@v4.3.1
      with:
        name: trc-amqp10_client-${{ matrix.metadata_store }}-${{ matrix.otp_version }}
        path: |
          ${{ inputs.trc }}
    - name: UPLOAD TEST ARTIFACTS
      if: always()
      uses: actions/upload-artifact@v4.3.1
      with:
        name: testlogs-amqp10_client-${{ matrix.metadata_store }}-${{ matrix.otp_version }}
        path: deps/amqp10_client/logs/*
