name: Test rabbitmq_management_agent
on:
  workflow_call:
    inputs:
      trc:
        required: true
        type: string
      hash:
        required: true
        type: string
      ignore-dialyze-errors:
        type: boolean
jobs:
  test:
    name: Test rabbitmq_management_agent
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        otp_version:
        - 26.2
        metadata_store:
        - mnesia
        - khepri
    timeout-minutes: 180
    env:
      SUCCESS_PATH: ${{ inputs.trc }}/${{ inputs.hash }}/rabbitmq_management_agent/${{ matrix.metadata_store }}/${{ matrix.otp_version }}
    steps:
    - name: FETCH TEST RESULT CACHE
      uses: actions/download-artifact@v4
      with:
        name: test-result-cache-subdir
        path: ${{ inputs.trc }}
    - name: CHECKOUT REPOSITORY
      uses: actions/checkout@v4
    - name: SETUP ERLANG/ELIXIR
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        elixir-version: 1.15
    - name: BUILD
      run: |
        make \
          RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
        mkdir -p ${{ env.SUCCESS_PATH }}
    - name: XREF
      run: |
        if [[ -f ${{ env.SUCCESS_PATH }}/xref ]]; then
          echo "xref already passed for this key ${{ inputs.hash }}"
        else
          make -C deps/rabbitmq_management_agent \
              xref \
              RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
          touch ${{ env.SUCCESS_PATH }}/xref
        fi
    - name: DIALYZE
      run: |
        if [[ -f ${{ env.SUCCESS_PATH }}/dialyze ]]; then
          echo "dialyze already passed for this key ${{ inputs.hash }}"
        else
          make -C deps/rabbitmq_management_agent \
              dialyze \
              RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
          touch ${{ env.SUCCESS_PATH }}/dialyze
        fi
      continue-on-error: ${{ inputs.ignore-dialyze-errors }}
    - name: EUNIT
      run: |
        if [[ -f ${{ env.SUCCESS_PATH }}/eunit ]]; then
          echo "eunit already passed for this key ${{ inputs.hash }}"
        else
          make -C deps/rabbitmq_management_agent \
              eunit \
              RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
          touch ${{ env.SUCCESS_PATH }}/eunit
        fi
    - name: CT exometer_slide
      run: |
        if [[ -f ${{ env.SUCCESS_PATH }}/ct-exometer_slide ]]; then
          echo "ct-exometer_slide already passed for this key ${{ inputs.hash }}"
        else
          make -C deps/rabbitmq_management_agent \
              ct-exometer_slide \
              RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
          touch ${{ env.SUCCESS_PATH }}/ct-exometer_slide
        fi
    - name: CT metrics
      run: |
        if [[ -f ${{ env.SUCCESS_PATH }}/ct-metrics ]]; then
          echo "ct-metrics already passed for this key ${{ inputs.hash }}"
        else
          make -C deps/rabbitmq_management_agent \
              ct-metrics \
              RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
          touch ${{ env.SUCCESS_PATH }}/ct-metrics
        fi
    - name: CT rabbit_mgmt_gc
      run: |
        if [[ -f ${{ env.SUCCESS_PATH }}/ct-rabbit_mgmt_gc ]]; then
          echo "ct-rabbit_mgmt_gc already passed for this key ${{ inputs.hash }}"
        else
          make -C deps/rabbitmq_management_agent \
              ct-rabbit_mgmt_gc \
              RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
          touch ${{ env.SUCCESS_PATH }}/ct-rabbit_mgmt_gc
        fi
    - name: CT rabbit_mgmt_slide
      run: |
        if [[ -f ${{ env.SUCCESS_PATH }}/ct-rabbit_mgmt_slide ]]; then
          echo "ct-rabbit_mgmt_slide already passed for this key ${{ inputs.hash }}"
        else
          make -C deps/rabbitmq_management_agent \
              ct-rabbit_mgmt_slide \
              RABBITMQ_METADATA_STORE=${{ matrix.metadata_store }}
          touch ${{ env.SUCCESS_PATH }}/ct-rabbit_mgmt_slide
        fi
    - name: SAVE CACHE COPY
      uses: actions/upload-artifact@v4.3.1
      with:
        name: trc-rabbitmq_management_agent-${{ matrix.metadata_store }}-${{ matrix.otp_version }}
        path: |
          ${{ inputs.trc }}
    - name: UPLOAD TEST ARTIFACTS
      if: always()
      uses: actions/upload-artifact@v4.3.1
      with:
        name: testlogs-rabbitmq_management_agent-${{ matrix.metadata_store }}-${{ matrix.otp_version }}
        path: deps/rabbitmq_management_agent/logs/*
