name: Update OTP Patch Versions for Bazel Based Workflows
on:
  schedule:
  - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  update-toolchains:
    name: Update OTP Versions
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        include:
        - erlang_version: "25.0"
          name: '25_0'
        - erlang_version: "25.1"
          name: '25_1'
    timeout-minutes: 10
    steps:
    - name: CHECKOUT REPOSITORY
      uses: actions/checkout@v3
    - name: SKIP IF THE PR ALREADY EXISTS
      id: check-for-branch
      run: |
        set +e
        git ls-remote --exit-code --heads origin bump-otp-${{ matrix.erlang_version }}
        echo "::set-output name=c::$?"
    - name: DETERMINE LATEST PATCH & SHA
      if: steps.check-for-branch.outputs.c != 0
      id: fetch-version
      run: |
        TAG_NAME=$(curl -s GET https://api.github.com/repos/erlang/otp/tags?per_page=100 \
          | jq -r 'map(select(.name | contains("OTP-${{ matrix.erlang_version }}"))) | first | .name')
        VERSION=${TAG_NAME#OTP-}

        ARCHIVE_URL="https://github.com/erlang/otp/releases/download/${TAG_NAME}/otp_src_${VERSION}.tar.gz"
        wget --continue --quiet --output-document="/tmp/OTP.tar.gz" "${ARCHIVE_URL}"
        SHA=$(shasum -a 256 "/tmp/OTP.tar.gz" | awk '{print $1}')

        if [ -z "${SHA}" ]; then
          echo "Failed to determine SHA for ${TAG_NAME}"
          exit 1
        fi

        echo "::set-output name=VERSION::${VERSION}"
        echo "::set-output name=SHA::${SHA}"
    - name: MODIFY VERSION FILE
      if: steps.check-for-branch.outputs.c != 0
      run: |
        sudo npm install --global --silent @bazel/buildozer

        OLD_SHA="$(cat MODULE.bazel | buildozer 'print sha256' -:${{ matrix.name }})"
        OLD_VERSION="$(cat MODULE.bazel | buildozer 'print version' -:${{ matrix.name }})"

        echo "$(cat MODULE.bazel | buildozer 'set sha256 "${{ steps.fetch-version.outputs.SHA }}"' -:${{ matrix.name }})" > MODULE.bazel
        echo "$(cat MODULE.bazel | buildozer 'set version "${{ steps.fetch-version.outputs.VERSION }}"' -:${{ matrix.name }})" > MODULE.bazel

        echo "$(cat WORKSPACE | buildozer 'set downloaded_file_path "OTP-${{ steps.fetch-version.outputs.VERSION }}.tar.gz"' -:otp_src_${{ matrix.name }})" > WORKSPACE
        echo "$(cat WORKSPACE | buildozer 'set urls ["https://github.com/erlang/otp/archive/OTP-${{ steps.fetch-version.outputs.VERSION }}.tar.gz"]' -:otp_src_${{ matrix.name }})" > WORKSPACE
        echo "$(cat WORKSPACE | buildozer 'set sha256 "${{ steps.fetch-version.outputs.SHA2 }}"' -:otp_src_${{ matrix.name }})" > WORKSPACE

        sed -i"_orig" "s/${OLD_SHA}/${{ steps.fetch-version.outputs.SHA }}" WORKSPACE
        sed -i"_orig" "s/${OLD_VERSION}/${{ steps.fetch-version.outputs.VERSION }}" WORKSPACE
        rm *_orig

        set -x
        git diff
    - name: CREATE PULL REQUEST
      if: steps.check-for-branch.outputs.c != 0
      uses: peter-evans/create-pull-request@v4.2.0
      with:
        token: ${{ secrets.REPO_SCOPED_TOKEN }}
        committer: GitHub <noreply@github.com>
        author: GitHub <noreply@github.com>
        title: Adopt otp ${{ steps.fetch-version.outputs.VERSION }}
        commit-message: |
          Adopt otp ${{ steps.fetch-version.outputs.VERSION }}
        labels: |
          backport-v3.11.x
          backport-v3.10.x
          backport-v3.9.x
          backport-v3.8.x
        branch: bump-otp-${{ matrix.erlang_version }}
        delete-branch: true
